### ISSUE TITLE
app开启时奔溃了

### ISSUE THREAD

**Issue by suojiang** [wangdan/AisenWeiBo#22]
![Uploading issue.png…]()

04-15 10:32:46.992 14140-14140/org.aisen.weibo.sina E/CrashReport: sys default last handle start!
04-15 10:32:46.997 14140-14140/org.aisen.weibo.sina E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.aisen.weibo.sina, PID: 14140
                                                                      java.lang.RuntimeException: Unable to create application com.android.tools.fd.runtime.BootstrapApplication: android.database.sqlite.SQLiteException: no such table: org_aisen_weibo_sina_support_bean_LogedinAccountBean (code 1): , while compiling: SELECT uid, $change, accessToken, account, advancedToken, cookie, groups, password, unreadCount, user, $change, error, error_code, $change, pagingIndex, endPaging, fromCache, outofdate FROM org_aisen_weibo_sina_support_bean_LogedinAccountBean
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4606)
                                                                          at android.app.ActivityThread.access$1500(ActivityThread.java:148)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5310)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
                                                                       Caused by: android.database.sqlite.SQLiteException: no such table: org_aisen_weibo_sina_support_bean_LogedinAccountBean (code 1): , while compiling: SELECT uid, $change, accessToken, account, advancedToken, cookie, groups, password, unreadCount, user, $change, error, error_code, $change, pagingIndex, endPaging, fromCache, outofdate FROM org_aisen_weibo_sina_support_bean_LogedinAccountBean
                                                                          at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                          at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                                          at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                                          at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                          at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                          at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                          at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                          at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                                          at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
                                                                          at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
                                                                          at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1240)
                                                                          at org.aisen.android.component.orm.SqliteUtility.select(SqliteUtility.java:118)
                                                                          at org.aisen.android.component.orm.SqliteUtility.select(SqliteUtility.java:93)
                                                                          at org.aisen.weibo.sina.support.utils.AccountUtils.getLogedinAccount(AccountUtils.java:39)
                                                                          at org.aisen.weibo.sina.base.MyApplication.onCreate(MyApplication.java:58)
                                                                          at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:326)
                                                                          at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1034)
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4603)
                                                                          at android.app.ActivityThread.access$1500(ActivityThread.java:148) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:135) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5310) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by wangdan** [comment]
估计是studio编译自动产生的字段$change导致建表失败，library现在是aar了，晚上我更新一下，明天你试试。library源码也同步更新上去。
