### ISSUE TITLE
系统升级到6.0  AisenTextView  setText  出错

### ISSUE THREAD

**Issue by xiaobohuo** [wangdan/AisenWeiBo#26]
Process: org.aisen.weibo.sina, PID: 19346
                                                                      java.lang.AbstractMethodError: abstract method "int android.text.ParcelableSpan.getSpanTypeIdInternal()"
                                                                          at android.text.TextUtils.writeToParcel(TextUtils.java:653)
                                                                          at android.os.Parcel.writeCharSequence(Parcel.java:576)
                                                                          at android.view.accessibility.AccessibilityNodeInfo.writeToParcel(AccessibilityNodeInfo.java:2701)
                                                                          at android.os.Parcel.writeParcelable(Parcel.java:1437)
                                                                          at android.view.accessibility.AccessibilityEvent.writeAccessibilityRecordToParcel(AccessibilityEvent.java:1177)
                                                                          at android.view.accessibility.AccessibilityEvent.writeToParcel(AccessibilityEvent.java:1139)
                                                                          at android.view.accessibility.IAccessibilityManager$Stub$Proxy.sendAccessibilityEvent(IAccessibilityManager.java:233)
                                                                          at android.view.accessibility.AccessibilityManager.sendAccessibilityEvent(AccessibilityManager.java:320)
                                                                          at android.view.ViewRootImpl.requestSendAccessibilityEvent(ViewRootImpl.java:6621)
                                                                          at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:880)
                                                                          at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:880)
                                                                          at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:880)
                                                                          at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:880)
                                                                          at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:880)
                                                                          at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:880)
                                                                          at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:880)
                                                                          at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:880)
                                                                          at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:880)
                                                                          at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:880)
                                                                          at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:880)
                                                                          at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:880)
                                                                          at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:880)
                                                                          at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:880)
                                                                          at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:880)
                                                                          at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5867)
                                                                          at android.view.View.sendAccessibilityEventUnchecked(View.java:5846)
                                                                          at android.view.View$SendViewStateChangedAccessibilityEvent.run(View.java:22478)
                                                                          at android.view.View$SendViewStateChangedAccessibilityEvent.runOrPost(View.java:22511)
                                                                          at android.view.View.notifyViewAccessibilityStateChangedIfNeeded(View.java:8836)
                                                                          at android.widget.TextView.setText(TextView.java:4365)
                                                                          at android.widget.TextView.setText(TextView.java:4216)
                                                                          at android.widget.TextView.setText(TextView.java:4191)
                                                                          at org.aisen.weibo.sina.ui.widget.AisenTextView$EmotionTask.onProgressUpdate(AisenTextView.java:251)
                                                                          at org.aisen.weibo.sina.ui.widget.AisenTextView$EmotionTask.onProgressUpdate(AisenTextView.java:144)
                                                                          at org.aisen.android.network.task.WorkTask$InternalHandler.handleMessage(WorkTask.java:399)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:168)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5885)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

**Comment by huangjinhong** [comment]
6.0.1上我运行也出现同样的兼容性问题
