### ISSUE TITLE
com.alibaba.fastjson已经成功引入，但是运行时报找不到包

### ISSUE THREAD

**Issue by hejunbinlan** [wangdan/AisenWeiBo#9]
/Users/test/workspace-android-studio/AisenWeiBo-master/app/src/main/java/org/aisen/weibo/sina/sinasdk/SinaSDK.java
Error:(12, 28) 错误: 程序包com.alibaba.fastjson不存在
Error:(1233, 31) 错误: 找不到符号
符号:   变量 JSON
位置: 类 SinaSDK
/Users/test/workspace-android-studio/AisenWeiBo-master/app/src/main/java/org/aisen/weibo/sina/sinasdk/http/HttpsUtility.java
Error:(5, 28) 错误: 程序包com.alibaba.fastjson不存在
Error:(144, 24) 错误: 找不到符号
符号:   变量 JSON
位置: 类 HttpsUtility
Error:(304, 14) 错误: 找不到符号
符号:   变量 JSON
位置: 类 HttpsUtility
Error:(364, 15) 错误: 找不到符号
符号:   变量 JSON
位置: 类 HttpsUtility
/Users/test/workspace-android-studio/AisenWeiBo-master/app/src/main/java/org/aisen/weibo/sina/support/biz/BaseBizlogic.java
Error:(5, 28) 错误: 程序包com.alibaba.fastjson不存在
Error:(112, 43) 错误: 找不到符号
符号:   变量 JSON
位置: 类 BaseBizlogic
/Users/test/workspace-android-studio/AisenWeiBo-master/app/src/main/java/org/aisen/weibo/sina/support/db/PublishDB.java
Error:(10, 28) 错误: 程序包com.alibaba.fastjson不存在
Error:(33, 47) 错误: 找不到符号
符号:   变量 JSON
位置: 类 PublishDB
Error:(33, 88) 错误: 找不到符号
符号:   变量 JSON
位置: 类 PublishDB
Error:(33, 130) 错误: 找不到符号
符号:   变量 JSON
位置: 类 PublishDB
/Users/test/workspace-android-studio/AisenWeiBo-master/app/src/main/java/org/aisen/weibo/sina/support/sdk/BizLogic.java
Error:(5, 28) 错误: 程序包com.alibaba.fastjson不存在
Error:(104, 43) 错误: 找不到符号
符号:   变量 JSON
位置: 类 BizLogic
/Users/test/workspace-android-studio/AisenWeiBo-master/app/src/main/java/org/aisen/weibo/sina/support/utils/AdTokenUtils.java
Error:(3, 28) 错误: 程序包com.alibaba.fastjson不存在
Error:(68, 41) 错误: 找不到符号
符号:   变量 JSON
位置: 类 LoadAdTokenTask
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
16 个错误
Error:Execution failed for task ':app:compileDebugJava'.
> Compilation failed; see the compiler error output for details.

**Comment by hzy87email** [comment]
@hejunbinlan 同样遇到此问题，目前在解决中，如果你解决了可以告诉我啊~

**Comment by hzy87email** [comment]
@hejunbinlan https://github.com/wangdan/AisenWeiBo/issues/6 移步这里，我已经解决了，在library-rom下面的build.gradle里面 compile 'com.alibaba:fastjson:1.2.6' 改成这个即可~

**Comment by rexcheung** [comment]
楼上正解

**Comment by lyyandroid** [comment]
求大神QQ 问下问题

**Comment by yanjuncq** [comment]
@hzy87email 肥肠感谢

**Comment by WayneLiang** [comment]
我也遇到同样问题，而且修改后编译通过了，但运行时就出错

**Comment by jackLi93** [comment]
在build.gradle（Moudle-library-orm）文件下添加依赖：compile 'com.alibaba:fastjson:1.2.8'

**Comment by loechove** [comment]
大家有遇到发多图会崩溃的情景么,用这个开源项目我会出现这种情况,但是豌豆荚上的apk没有问题,请问改动了哪里导致的

**Comment by loechove** [comment]
错误日志贴出:
03-18 13:23:51.453 29764-29827/org.aisen.weibo.sina E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                      Process: org.aisen.weibo.sina, PID: 29764
                                                                      java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                          at org.aisen.android.network.task.WorkTask$3.done(WorkTask.java:175)
                                                                          at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                          at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                          at org.aisen.android.network.task.WorkTask$SerialExecutor$1.run(WorkTask.java:97)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.aisen.weibo.sina.sinasdk.bean.UploadPictureResultBean.getPic_id()' on a null object reference
                                                                          at # **`org.aisen.weibo.sina.support.publisher.PublishManager$PublishTask.workInBackground(PublishManager.java:422)`**
                                                                          at **org.aisen.weibo.sina.support.publisher.PublishManager$PublishTask.workInBackground(PublishManager.java:267)**
                                                                          at org.aisen.android.network.task.WorkTask.doInBackground(WorkTask.java:247)
                                                                          at org.aisen.android.network.task.WorkTask.access$400(WorkTask.java:25)
                                                                          at org.aisen.android.network.task.WorkTask$2.call(WorkTask.java:161)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at org.aisen.android.network.task.WorkTask$SerialExecutor$1.run(WorkTask.java:97) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                          at java.lang.Thread.run(Thread.java:818) 

- 

- 

-
